name: .NET Build and Publish NuGet to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x.x'  # Specify your .NET version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack NuGet
      run: dotnet pack --no-build --configuration Release --output ./nupkgs

    - name: Publish NuGet Package to GitHub Packages
      run: dotnet nuget push "./nupkgs/*.nupkg" --source "github"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
